"""initial

Revision ID: 2cb7bae4530d
Revises: 
Create Date: 2026-03-18 22:38:30.299887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cb7bae4530d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("role IN ('admin', 'user')", name='ck_user_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('avize',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numar_complet', sa.String(length=50), nullable=False),
    sa.Column('numar_secvential', sa.Integer(), nullable=False),
    sa.Column('an_aviz', sa.Integer(), nullable=False),
    sa.Column('data_aviz', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('beneficiar_nume', sa.String(length=200), nullable=True),
    sa.Column('beneficiar_cif', sa.String(length=50), nullable=True),
    sa.Column('beneficiar_telefon', sa.String(length=50), nullable=True),
    sa.Column('beneficiar_email', sa.String(length=200), nullable=True),
    sa.Column('auto_nr', sa.String(length=20), nullable=False),
    sa.Column('auto_marca', sa.String(length=100), nullable=False),
    sa.Column('auto_model', sa.String(length=100), nullable=False),
    sa.Column('auto_serie_sasiu', sa.String(length=100), nullable=True),
    sa.Column('auto_serie_motor', sa.String(length=100), nullable=True),
    sa.Column('auto_an_fabricatie', sa.Integer(), nullable=True),
    sa.Column('auto_motorizare', sa.String(length=100), nullable=True),
    sa.Column('auto_km', sa.Integer(), nullable=True),
    sa.Column('defect_reclamat', sa.Text(), nullable=True),
    sa.Column('defecte_constatate', sa.Text(), nullable=True),
    sa.Column('tva_snapshot', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numar_complet'),
    sa.UniqueConstraint('numar_secvential', 'an_aviz', name='uq_aviz_nr_an')
    )
    op.create_table('aviz_materiale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aviz_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('denumire', sa.String(length=300), nullable=True),
    sa.Column('um', sa.String(length=20), nullable=True),
    sa.Column('cantitate', sa.Float(), nullable=True),
    sa.Column('pret_unitar', sa.Float(), nullable=True),
    sa.Column('valoare', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['aviz_id'], ['avize.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aviz_servicii',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aviz_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('denumire', sa.String(length=300), nullable=True),
    sa.Column('um', sa.String(length=20), nullable=True),
    sa.Column('cantitate', sa.Float(), nullable=True),
    sa.Column('pret_unitar', sa.Float(), nullable=True),
    sa.Column('valoare', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['aviz_id'], ['avize.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aviz_servicii')
    op.drop_table('aviz_materiale')
    op.drop_table('avize')
    op.drop_table('users')
    op.drop_table('settings')
    # ### end Alembic commands ###
